### PR TITLE
Remove erlsha2 dep

### PR DESCRIPTION
**Pull request by sata**

### CODE REVIEW

**Comment by maxkuzmins** [comment]
GG WP

**Comment by maxkuzmins** [comment]
@sata I believe `base16` needs to be added to `applications` of `current.app.src`.

**Comment by horvand** [comment]
@sata Can you squash the commits together a bit?

**Comment by sata** [comment]
@horvand yeah,  I  squashed away 2 commits. I don't mind squashing more tbh.

**Pull request merged**
